### ISSUE TITLE
Uncaught TypeError: Cannot read property 'query' of undefined

### ISSUE THREAD

**Issue by Pitoyable** [Hube2/acf-filters-and-functions#17]
Hi !

I came across your solution to add a default value field to the image field type and it seems to be exactly what I'm looking for.
Thanks for that ! 
Nevertheless when I try to open the file manager by clicking on the new button :
![image](https://user-images.githubusercontent.com/22983519/49004973-de65bb00-f165-11e8-9b69-b367314303b9.png)
An error occure : 
![image](https://user-images.githubusercontent.com/22983519/49005028-f76e6c00-f165-11e8-83a8-53561fd7a763.png)

Is it because of a new version of ACF or is it comming from me ? 
The code I used :
```
function add_default_value_to_image_field( $field ) {
        acf_render_field_setting( $field, array(
		'label'			=> 'Image par défaut',
		'type'			=> 'image',
		'name'			=> 'default_value',
	));
}
add_action('acf/render_field_settings/type=image', 'add_default_value_to_image_field');
```

Thanks

**Comment by Hube2** [comment]
I don't know to be honest. This could have something to do with the new ACF JS API, or with something else. There can be an error because the scripts needed to select and image are not added to the page. You need to save the field group and then you'll be able to select an image.  I explain this problem here https://acfextras.com/default-image-for-image-field/

**Comment by Pitoyable** [comment]
Saving the field group and then adding the image works. Thanks for your quick answer !
